# -*- coding: utf-8 -*-
"""全量扫描：AIGC 生成标记 + 双重编码乱码（含 docx/xlsx 二进制文档）。

AIGC 标记模式：YAML `AIGC:` 块（ContentProducer / ContentPropagator / ProduceID /
PropagateID / ReservedCode1 / ReservedCode2）、`> AI 生成` 引用块、以及泛化文本
（AI生成 / Generated by AI / AI-generated / Midjourney / DALL·E 等）。
乱码模式：U+FFFD 替换符、Â/Ã/â/€/™ 等 GB18030 误读残留、以及常见转义序列。
"""
import io
import os
import re
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 跳过目录
SKIP_DIRS = {"node_modules", ".git", ".workbuddy", ".temp", "mpt-storage",
             "bench", "scenes", "assets", "新建文件夹", "reports", "__pycache__"}

AIGC_PAT = re.compile(
    r"AIGC\s*:|ContentProducer|ContentPropagator|ProduceID|PropagateID|"
    r"ReservedCode1|ReservedCode2|AI\s*生成|由\s*AI\s*生成|Generated\s+by\s+AI|"
    r"AI-generated|Midjourney|DALL[.\u00b7]?E|Stable\s*Diffusion|"
    r"ChatGPT\s*生成|文心一格|通义万相", re.I)

# 常见双重编码乱码片段（UTF-8 字节被 GB18030 误读）
MOJI_PAT = re.compile(
    r"[\ufffd]|Ã[©¨©ª©]|Â[³©ª]|â[€\u0098]|Ã¢|Ã©|Ã¨|Ã§|Ã±|Ã¶|Ã¼|â€|"
    r"Ã\u00a0|Â |ï¿½")


def scan_text(s):
    aigc = AIGC_PAT.findall(s)
    moji = MOJI_PAT.findall(s)
    return aigc, moji


def scan_docx(path):
    """解压 docx/xlsx，扫描 document.xml / sharedStrings.xml 等文本部分。"""
    found = []
    try:
        with zipfile.ZipFile(path) as z:
            for name in z.namelist():
                if name.endswith(".xml") and ("document" in name or "sharedStrings" in name
                                              or "core" in name or "app" in name):
                    data = z.read(name).decode("utf-8", "replace")
                    a, m = scan_text(data)
                    if a or m:
                        found.append((name, len(a), len(m)))
    except Exception as e:
        return [("ERR:" + str(e)[:40], 0, 0)]
    return found


def main():
    print("扫描根目录:", ROOT)
    print("=" * 78)
    hits = []
    moji_hits = []
    docx_hits = []

    for dp, dn, fn in os.walk(ROOT):
        dn[:] = [x for x in dn if x not in SKIP_DIRS]
        for f in fn:
            p = os.path.join(dp, f)
            rel = os.path.relpath(p, ROOT)
            if f.endswith((".docx", ".xlsx")):
                r = scan_docx(p)
                if r:
                    docx_hits.append((rel, r))
                continue
            if not f.endswith((".md", ".html", ".js", ".json", ".yml",
                               ".yaml", ".txt", ".css", ".py", ".ps1",
                               ".csv", ".ts", ".tsx", ".vue")):
                continue
            try:
                s = io.open(p, encoding="utf-8", errors="replace").read()
            except Exception:
                continue
            a, m = scan_text(s)
            if a:
                hits.append((rel, a[:6]))
            if m:
                moji_hits.append((rel, len(m)))

    print("\n【AIGC 标记 - 文本文件】")
    if hits:
        for rel, a in hits:
            print(f"  {rel:<50} {a}")
    else:
        print("  无")

    print("\n【双重编码乱码 - 文本文件】")
    if moji_hits:
        for rel, n in moji_hits:
            print(f"  {rel:<50} {n} 处")
    else:
        print("  无")

    print("\n【AIGC 标记/乱码 - docx/xlsx 二进制文档】")
    if docx_hits:
        for rel, parts in docx_hits:
            for nm, a, m in parts:
                print(f"  {rel:<46} [{nm}] AIGC={a} 乱码={m}")
    else:
        print("  无")

    print("\n结论:", "存在需处理项" if (hits or moji_hits or docx_hits) else "全清")


if __name__ == "__main__":
    main()
